service: prismic-photos

provider:
  name: google
  runtime: nodejs8
  project: ourclan-220709
  region: europe-west1
  credentials: ~/.gcloud/ourclan.json

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

functions:
  get_albums:
    handler: albums
    events:
      - http: path
  login:
    handler: login
    events:
      - http: path

plugins:
  - serverless-webpack
  - serverless-google-cloudfunctions
