service: prismic-photos

provider:
  name: google
  runtime: nodejs8
  project: festive-airway-216914
  region: europe-west1
  credentials: google-credentials.json

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

functions:
  get_rules:
    handler: rules
    events:
      - http: path

plugins:
  - serverless-webpack
  - serverless-google-cloudfunctions
  - serverless-offline
