service: parse-mechanics

provider:
  name: google
  runtime: nodejs8
  project: festive-airway-216914
  region: europe-west1
  credentials: ~/google-credentials.json

functions:
  parseRules:
    handler: rules
    events:
      - http: path

plugins:
  - serverless-google-cloudfunctions